// Generates docs/API.md (route list) and docs/PERMISSION_MATRIX.md from the code, so they never drift.
import { writeFileSync } from 'node:fs';
import { buildApp } from '../src/app.ts';
import { ROLE_PERMISSIONS, STAFF_ROLES } from '../src/rbac.ts';

const routes: { m: string; u: string }[] = [];
const app = await buildApp({ onRoute: (r) => { for (const m of ([] as string[]).concat(r.method as any)) if (m !== 'HEAD' && m !== 'OPTIONS') routes.push({ m, u: r.url }); } });
await app.ready();
const groups: Record<string, string[]> = { 'Auth & account': ['/api/v1/auth', '/api/v1/users', '/api/v1/notifications'], 'Catalogue, places & pricing': ['/api/v1/config', '/api/v1/services', '/api/v1/places', '/api/v1/coverage', '/api/v1/fares', '/api/v1/promotions'],
  'Bookings & trips': ['/api/v1/bookings'], 'Drivers': ['/api/v1/drivers', '/api/v1/files'], 'Payments': ['/api/v1/payments', '/api/v1/webhooks', '/api/v1/dev'], 'Support & safety': ['/api/v1/support', '/api/v1/safety', '/share'],
  'Corporate': ['/api/v1/businesses'], 'Fleets': ['/api/v1/fleets'], 'Admin: finance': ['/api/v1/admin/finance'], 'Admin: operations': ['/api/v1/admin'], 'Health': ['/health', '/ready'] };
const used = new Set<string>(); let md = '# API reference\n\n> Generated by `npm run docs` from the registered routes. Base path `/api/v1`. JSON in/out. Errors: `{ "error": { "code", "message", "details" } }`.\n> Auth: `Authorization: Bearer <access token>`. State-changing booking/payment calls accept an `Idempotency-Key` header. Interactive details live in the zod schemas next to each route (`src/routes/*.ts`).\n\n';
for (const [g, prefixes] of Object.entries(groups)) {
  const rows = routes.filter((r) => !used.has(r.m + r.u) && prefixes.some((p) => r.u === p || r.u.startsWith(p + '/') || r.u.startsWith(p))).sort((a, b) => a.u.localeCompare(b.u) || a.m.localeCompare(b.m));
  rows.forEach((r) => used.add(r.m + r.u)); if (!rows.length) continue;
  md += `## ${g}\n\n| Method | Path |\n|---|---|\n` + rows.map((r) => `| ${r.m} | \`${r.u.replace('/api/v1', '')}\` |`).join('\n') + '\n\n';
}
writeFileSync(new URL('../../docs/API.md', import.meta.url), md);

let pm = '# Role and permission matrix\n\n> Generated from `src/rbac.ts`. Permissions are enforced on the server for every endpoint; object-level checks (own bookings, own fleet, own company) apply on top. `*` = everything.\n\n## Staff roles (web console, mandatory TOTP MFA)\n\n| Role | Permissions |\n|---|---|\n';
for (const r of STAFF_ROLES) pm += `| \`${r}\` | ${ROLE_PERMISSIONS[r].map((p) => '`' + p + '`').join(', ')} |\n`;
pm += `\n## End-user roles (mobile app)\n\n| Role | Scope |\n|---|---|\n| \`passenger\` | Own profile, saved places, bookings, payments, ratings, support cases. Default for every new account. |\n| \`driver\` | Own driver profile/vehicle/documents, offers and trips assigned to them, own earnings/wallet/payouts. Dispatch only after approval. |\n| \`fleet_manager\` | Only the fleet(s) they belong to: drivers, vehicles, trips, earnings, invites, fleet payouts (owner only). |\n| \`corporate_admin\` | Their company: members, policy, all company bookings, statements, invoices. |\n| \`corporate_booker\` / employee | Book on the company account within policy and personal spending limit; see only their own company trips. |\n\n## Maker-checker rules (two different people)\n\n| Action | Maker | Checker |\n|---|---|---|\n| Fare change | \`pricing.manage\` | \`pricing.approve\` (not the maker) |\n| Commission change / exemption | \`pricing.manage\` | \`pricing.approve\` (not the maker) |\n| Refund | \`finance.refund.request\` | \`finance.refund.approve\` (not the requester) |\n| Large payout (>= configurable threshold) | \`finance.payout.review\` | \`finance.payout.approve\` (not the reviewer), release by someone other than the approver |\n| Enable regulated flags (surge, negotiated fares, wallet) | any \`settings.manage\` holder cannot | \`super_admin\` only |\n`;
writeFileSync(new URL('../../docs/PERMISSION_MATRIX.md', import.meta.url), pm);
console.log(`routes documented: ${routes.length}`);
await app.close(); process.exit(0);
