// Notification templates for credit, loyalty, deposit, claims and the USSD channel (round 3). Merged into DEFAULT_TEMPLATES (i18n.ts).
// Every template exists in en, rw and fr with identical placeholders; a user only ever sees one language.
type L = 'en' | 'rw' | 'fr';
type Tpl = { title: string; body: string };
const T = (en: [string, string], rw: [string, string], fr: [string, string]): Record<L, Tpl> => ({
  en: { title: en[0], body: en[1] }, rw: { title: rw[0], body: rw[1] }, fr: { title: fr[0], body: fr[1] },
});

export const MONEY_LABELS: Record<string, Record<L, string>> = {
  bronze: { en: 'Bronze', rw: 'Bronze', fr: 'Bronze' }, silver: { en: 'Silver', rw: 'Silver', fr: 'Argent' }, gold: { en: 'Gold', rw: 'Gold', fr: 'Or' },
};

export const MONEY_TEMPLATES: Record<string, Record<L, Tpl>> = {
  credit_received: T(['Credit added', '{{amount}} RWF was added to your Abasare credit. You can use it on your next trip.'],
    ['Wongerewe amafaranga', 'Wongerewe {{amount}} RWF yo gukoresha mu ngendo kuri konti yawe ya Abasare. Ushobora kuyakoresha ku rugendo rutaha.'],
    ['Crédit ajouté', '{{amount}} RWF ont été ajoutés à votre crédit Abasare. Vous pouvez l\'utiliser pour votre prochaine course.']),
  credit_expiring: T(['Credit expiring soon', '{{amount}} RWF of your credit expires on {{date}}. Use it before then.'],
    ['Amafaranga yawe agiye kurangira', '{{amount}} RWF y\'amafaranga yawe yo gukoresha izarangira ku itariki {{date}}. Yikoreshe mbere yaho.'],
    ['Crédit bientôt expiré', '{{amount}} RWF de votre crédit expirent le {{date}}. Utilisez-les avant cette date.']),
  loyalty_tier_up: T(['New loyalty level', 'Congratulations! You are now {{status}} on Abasare.'],
    ['Urwego rushya', 'Ishimwe! Ubu uri ku rwego rwa {{status}} muri Abasare.'],
    ['Nouveau niveau de fidélité', 'Félicitations ! Vous êtes maintenant {{status}} sur Abasare.']),
  deposit_paid: T(['Deposit received', 'Your deposit of {{amount}} RWF was received. We are now finding your Abasare.'],
    ['Avansi yakiriwe', 'Twakiriye avansi yawe ya {{amount}} RWF. Turimo gushaka Abasare wawe.'],
    ['Acompte reçu', 'Votre acompte de {{amount}} RWF a bien été reçu. Nous recherchons maintenant votre Abasare.']),
  deposit_failed: T(['Deposit not paid', 'Your deposit payment did not go through. Try again, or pay with your credit.'],
    ['Avansi ntiyishyuwe', 'Kwishyura avansi ntibyagenze neza. Ongera ugerageze, cyangwa wishyure ukoresheje amafaranga yawe yo gukoresha.'],
    ['Acompte non payé', 'Le paiement de votre acompte n\'a pas abouti. Réessayez, ou payez avec votre crédit.']),
  deposit_expired: T(['Booking cancelled', 'Your Abasare booking was cancelled because the deposit was not paid in time.'],
    ['Ubusabe bwahagaritswe', 'Ubusabe bwawe bwa Abasare bwahagaritswe kuko avansi itishyuwe ku gihe.'],
    ['Réservation annulée', 'Votre réservation Abasare a été annulée car l\'acompte n\'a pas été payé à temps.']),
  deposit_refunded: T(['Deposit returned', '{{amount}} RWF of your deposit was returned to you as credit.'],
    ['Avansi yagarutse', '{{amount}} RWF ya avansi yawe yagarutse nk\'amafaranga yo gukoresha mu ngendo.'],
    ['Acompte restitué', '{{amount}} RWF de votre acompte vous ont été restitués sous forme de crédit.']),
  deposit_late_credit: T(['Deposit kept as credit', 'Your deposit of {{amount}} RWF arrived after the booking closed. It was added to your credit.'],
    ['Avansi yabitswe', 'Avansi yawe ya {{amount}} RWF yageze ubusabe bwamaze gufungwa. Yongewe ku mafaranga yawe yo gukoresha.'],
    ['Acompte conservé en crédit', 'Votre acompte de {{amount}} RWF est arrivé après la clôture de la réservation. Il a été ajouté à votre crédit.']),
  claim_filed: T(['Claim received', 'Your claim {{ref}} was received. We will start reviewing it within {{hours}} hours.'],
    ['Ikirego cyakiriwe', 'Ikirego cyawe {{ref}} cyakiriwe. Tuzatangira kugisuzuma mu masaha {{hours}}.'],
    ['Réclamation reçue', 'Votre réclamation {{ref}} a été reçue. Nous commencerons son examen dans les {{hours}} heures.']),
  claim_received: T(['A claim concerns your trip', 'A claim {{ref}} was filed about a trip you took part in. Please reply in the app within {{hours}} hours.'],
    ['Hari ikirego ku rugendo rwawe', 'Ikirego {{ref}} cyatanzwe ku rugendo wagiyemo. Nyamuneka subiza muri porogaramu mu masaha {{hours}}.'],
    ['Une réclamation concerne votre course', 'Une réclamation {{ref}} a été déposée au sujet d\'une course à laquelle vous avez participé. Répondez dans l\'application sous {{hours}} heures.']),
  claim_info_requested: T(['More information needed', 'We need more information for your claim {{ref}}. Please answer in the app.'],
    ['Dukeneye andi makuru', 'Dukeneye andi makuru ku kirego cyawe {{ref}}. Nyamuneka subiza muri porogaramu.'],
    ['Informations complémentaires requises', 'Il nous faut plus d\'informations pour votre réclamation {{ref}}. Répondez dans l\'application.']),
  claim_accepted: T(['Claim accepted', 'Your claim {{ref}} was accepted for {{amount}} RWF.'],
    ['Ikirego cyemewe', 'Ikirego cyawe {{ref}} cyemewe ku mafaranga {{amount}} RWF.'],
    ['Réclamation acceptée', 'Votre réclamation {{ref}} a été acceptée pour {{amount}} RWF.']),
  claim_partially_accepted: T(['Claim partly accepted', 'Your claim {{ref}} was partly accepted for {{amount}} RWF. Open the app to see why.'],
    ['Ikirego cyemewe igice', 'Ikirego cyawe {{ref}} cyemewe igice ku mafaranga {{amount}} RWF. Fungura porogaramu urebe impamvu.'],
    ['Réclamation acceptée en partie', 'Votre réclamation {{ref}} a été acceptée en partie pour {{amount}} RWF. Ouvrez l\'application pour voir pourquoi.']),
  claim_rejected: T(['Claim not accepted', 'Your claim {{ref}} was not accepted. Open the app to see the reason.'],
    ['Ikirego nticyemewe', 'Ikirego cyawe {{ref}} nticyemewe. Fungura porogaramu urebe impamvu.'],
    ['Réclamation refusée', 'Votre réclamation {{ref}} n\'a pas été acceptée. Ouvrez l\'application pour en voir la raison.']),
  claim_settled: T(['Claim settled', 'Claim {{ref}} is settled for {{amount}} RWF.'],
    ['Ikirego cyarangiye', 'Ikirego {{ref}} cyarangiye, hishyuwe {{amount}} RWF.'],
    ['Réclamation réglée', 'La réclamation {{ref}} est réglée pour {{amount}} RWF.']),
  claim_reply_added: T(['New reply on your claim', 'The other party replied to claim {{ref}}. Open the app to read it.'],
    ['Igisubizo gishya ku kirego cyawe', 'Undi muntu yasubije ku kirego {{ref}}. Fungura porogaramu ukisome.'],
    ['Nouvelle réponse à votre réclamation', 'L\'autre partie a répondu à la réclamation {{ref}}. Ouvrez l\'application pour la lire.']),
  claim_reminder_reply: T(['Please reply to a claim', 'Reminder: please reply to claim {{ref}} in the app.'],
    ['Subiza ku kirego', 'Wibutswe: nyamuneka subiza ku kirego {{ref}} muri porogaramu.'],
    ['Merci de répondre à une réclamation', 'Rappel : merci de répondre à la réclamation {{ref}} dans l\'application.']),
  claim_reminder_info: T(['Your claim is waiting', 'Reminder: claim {{ref}} is waiting for the information we asked for.'],
    ['Ikirego cyawe kirategereje', 'Wibutswe: ikirego {{ref}} gitegereje amakuru twagusabye.'],
    ['Votre réclamation attend', 'Rappel : la réclamation {{ref}} attend les informations demandées.']),
  claim_sla_warning: T(['Claim needs a first response', 'Claim {{ref}} is close to its first-response deadline. Please review it.'],
    ['Ikirego gikeneye igisubizo', 'Ikirego {{ref}} kigiye kurenza igihe cyo gusubizwa bwa mbere. Nyamuneka cyisuzume.'],
    ['Réclamation à traiter', 'La réclamation {{ref}} approche de son délai de première réponse. Merci de l\'examiner.']),
  // ---- USSD riders have no app: these replace the normal template (same key + _ussd) and are always sent as SMS. Keep each under ~160 characters.
  booking_confirmed_ussd: T(['Abasare', 'Abasare: request {{ref}} received. We are finding a driver. Dial the same USSD code, option 2, to follow your trip.'],
    ['Abasare', 'Abasare: ubusabe {{ref}} bwakiriwe. Turashaka umushoferi. Ongera ukande kode ya USSD, hitamo 2 ukurikirane urugendo.'],
    ['Abasare', 'Abasare : demande {{ref}} reçue. Recherche d\'un chauffeur. Recomposez le code USSD, option 2, pour suivre.']),
  driver_assigned_ussd: T(['Abasare', 'Abasare: {{driver}} ({{plate}}) is coming. Dial the USSD code, option 2, to see your trip PIN.'],
    ['Abasare', 'Abasare: {{driver}} ({{plate}}) araje. Kanda kode ya USSD, hitamo 2 urebe PIN y\'urugendo.'],
    ['Abasare', 'Abasare : {{driver}} ({{plate}}) arrive. Composez le code USSD, option 2, pour voir le PIN.']),
  driver_arrived_ussd: T(['Abasare', 'Abasare: your driver arrived. Plate {{plate}}. Give the trip PIN (USSD option 2) before you ride.'],
    ['Abasare', 'Abasare: umushoferi yahageze. Plaque {{plate}}. Mubwire PIN y\'urugendo (USSD 2) mbere yo kwinjira.'],
    ['Abasare', 'Abasare : votre chauffeur est arrivé. Plaque {{plate}}. Donnez le PIN (USSD option 2) avant de monter.']),
  trip_completed_ussd: T(['Abasare', 'Abasare: trip {{ref}} is done. Fare {{fare}} RWF, pay cash to the driver. Thank you.'],
    ['Abasare', 'Abasare: urugendo {{ref}} rwarangiye. Igiciro {{fare}} RWF, ishyura umushoferi mu ntoki. Murakoze.'],
    ['Abasare', 'Abasare : course {{ref}} terminée. Tarif {{fare}} RWF, payez en espèces au chauffeur. Merci.']),
};
