// Settings for credit, loyalty, Abasare deposit, claims and USSD (round 3). Spread into SETTING_DEFAULTS (config.ts) and SETTING_META (settingsMeta.ts).
import type { SettingMeta } from './settingsMeta.js';

export const MONEY_DEFAULTS = {
  'wallet.enabled': true,
  'wallet.credit_expiry_days': 0,
  'wallet.max_balance': 500000,
  'wallet.adjust_approval_threshold': 50000,
  'referral.reward_credit': 0,
  'loyalty.enabled': true,
  'loyalty.earn_rwf_per_point': 100,
  'loyalty.redeem_rwf_per_100_points': 100,
  'loyalty.min_redeem_points': 500,
  'loyalty.silver_min_points': 2000,
  'loyalty.gold_min_points': 10000,
  'loyalty.silver_bonus_pct': 10,
  'loyalty.gold_bonus_pct': 25,
  'loyalty.silver_extra_grace_s': 30,
  'loyalty.gold_extra_grace_s': 60,
  'abasare.deposit_percent': 0,
  'abasare.deposit_timeout_min': 10,
  'claims.filing_window_hours': 72,
  'claims.sla_hours': 48,
  'claims.reply_hours': 48,
  'claims.info_reply_hours': 72,
  'claims.settlement_approval_threshold': 100000,
  'claims.max_evidence': 12,
  'claims.auto_close_days': 7,
  'ussd.enabled': true,
  'ussd.session_ttl_s': 120,
};

const W = 'Credit & loyalty', D = 'Drivers & Abasare', C = 'Claims', U = 'USSD';
export const MONEY_META: Record<keyof typeof MONEY_DEFAULTS, SettingMeta> = {
  'wallet.enabled': { group: W, label: 'Customer credit', desc: 'Lets customers spend credit (refunds, promotions, loyalty) on trips. Credit cannot be topped up with cash or withdrawn.', type: 'bool' },
  'wallet.credit_expiry_days': { group: W, label: 'Credit expiry', desc: 'New credit expires this many days after it is granted. 0 = never expires. Customers are reminded 7 days before.', unit: 'days', min: 0, max: 730 },
  'wallet.max_balance': { group: W, label: 'Maximum credit balance', desc: 'Promotional and manual credit cannot take a customer above this balance (refunds are never refused).', unit: 'RWF', min: 0, max: 100000000 },
  'wallet.adjust_approval_threshold': { group: W, label: 'Credit change needing a second approver', desc: 'Manual credit changes at or above this amount wait for a different person to approve.', unit: 'RWF', min: 0, max: 100000000 },
  'referral.reward_credit': { group: W, label: 'Referral reward as credit', desc: 'If above 0, referral rewards are paid as this much credit to each side instead of a one-time promo code. 0 = keep promo codes.', unit: 'RWF', min: 0, max: 50000 },
  'loyalty.enabled': { group: W, label: 'Loyalty points', desc: 'Customers earn points on completed trips.', type: 'bool' },
  'loyalty.earn_rwf_per_point': { group: W, label: 'Fare per point', desc: 'One point is earned for each this many RWF of fare.', unit: 'RWF', min: 1, max: 10000 },
  'loyalty.redeem_rwf_per_100_points': { group: W, label: 'Credit per 100 points', desc: 'How much credit 100 points are worth when redeemed.', unit: 'RWF', min: 1, max: 10000 },
  'loyalty.min_redeem_points': { group: W, label: 'Minimum points to redeem', desc: 'Points are redeemed in multiples of 100, at least this many.', unit: 'points', min: 100, max: 100000 },
  'loyalty.silver_min_points': { group: W, label: 'Silver tier from', desc: 'Lifetime points needed for Silver.', unit: 'points', min: 1, max: 10000000 },
  'loyalty.gold_min_points': { group: W, label: 'Gold tier from', desc: 'Lifetime points needed for Gold. Must be above the Silver threshold.', unit: 'points', min: 1, max: 10000000 },
  'loyalty.silver_bonus_pct': { group: W, label: 'Silver bonus points', desc: 'Extra points on each trip for Silver members.', unit: '%', min: 0, max: 300 },
  'loyalty.gold_bonus_pct': { group: W, label: 'Gold bonus points', desc: 'Extra points on each trip for Gold members.', unit: '%', min: 0, max: 300 },
  'loyalty.silver_extra_grace_s': { group: W, label: 'Silver extra free-cancel time', desc: 'Added to the free cancellation window.', unit: 'seconds', min: 0, max: 600 },
  'loyalty.gold_extra_grace_s': { group: W, label: 'Gold extra free-cancel time', desc: 'Added to the free cancellation window.', unit: 'seconds', min: 0, max: 600 },
  'abasare.deposit_percent': { group: D, label: 'Abasare deposit', desc: 'Percent of the estimated fare the customer pays before an Umusare is dispatched. 0 = no deposit. The deposit is applied to the final fare.', unit: '%', min: 0, max: 100 },
  'abasare.deposit_timeout_min': { group: D, label: 'Deposit payment time', desc: 'An unpaid deposit cancels the (unscheduled) booking after this long.', unit: 'minutes', min: 2, max: 120 },
  'claims.filing_window_hours': { group: C, label: 'Claim filing window', desc: 'A claim can be filed this long after the trip ended.', unit: 'hours', min: 1, max: 720 },
  'claims.sla_hours': { group: C, label: 'First response target', desc: 'Staff should start reviewing a claim within this time; a reminder goes out at 75%.', unit: 'hours', min: 1, max: 336 },
  'claims.reply_hours': { group: C, label: 'Right of reply', desc: 'The other party has this long to reply before a decision can be made.', unit: 'hours', min: 1, max: 336 },
  'claims.info_reply_hours': { group: C, label: 'Time to provide requested information', desc: 'How long the claimant has to answer an information request.', unit: 'hours', min: 1, max: 336 },
  'claims.settlement_approval_threshold': { group: C, label: 'Settlement needing a second approver', desc: 'Settlements at or above this amount wait for a different person to approve.', unit: 'RWF', min: 0, max: 100000000 },
  'claims.max_evidence': { group: C, label: 'Evidence files per claim', desc: 'Maximum uploaded photos or documents.', unit: 'files', min: 1, max: 40 },
  'claims.auto_close_days': { group: C, label: 'Close settled claims after', desc: 'Settled claims are closed automatically.', unit: 'days', min: 1, max: 90 },
  'ussd.enabled': { group: U, label: 'USSD booking', desc: 'Accepts requests from the USSD gateway.', type: 'bool' },
  'ussd.session_ttl_s': { group: U, label: 'USSD session lifetime', desc: 'A dialogue idle for longer than this starts again.', unit: 'seconds', min: 30, max: 600 },
};
