// Icon artwork. Cropped from the supplied designs (tabs, calendar, tickets, list icons) and redrawn in the same style (scripts/icons/build.mjs).
// `EMOJI_ICON` lets existing screens keep passing an emoji: it is swapped for the artwork; an emoji without artwork still renders as text.
import type { ImageSourcePropType } from 'react-native';

export const ICONS = {
  briefcase: require('../../assets/icons/briefcase.png'),
  bronze: require('../../assets/icons/bronze.png'),
  bulb: require('../../assets/icons/bulb.png'),
  calendar: require('../../assets/icons/calendar.png'),
  camera: require('../../assets/icons/camera.png'),
  captain: require('../../assets/icons/captain.png'),
  cars: require('../../assets/icons/cars.png'),
  cash: require('../../assets/icons/cash.png'),
  chart: require('../../assets/icons/chart.png'),
  check: require('../../assets/icons/check.png'),
  claims: require('../../assets/icons/claims.png'),
  clock: require('../../assets/icons/clock.png'),
  coins: require('../../assets/icons/coins.png'),
  compass: require('../../assets/icons/compass.png'),
  copy: require('../../assets/icons/copy.png'),
  credit: require('../../assets/icons/credit.png'),
  cross: require('../../assets/icons/cross.png'),
  drivers: require('../../assets/icons/drivers.png'),
  fare: require('../../assets/icons/fare.png'),
  flag: require('../../assets/icons/flag.png'),
  flame: require('../../assets/icons/flame.png'),
  folder: require('../../assets/icons/folder.png'),
  gold: require('../../assets/icons/gold.png'),
  help: require('../../assets/icons/help.png'),
  hero_art: require('../../assets/icons/hero_art.png'),
  idcard: require('../../assets/icons/idcard.png'),
  invite: require('../../assets/icons/invite.png'),
  link: require('../../assets/icons/link.png'),
  lock: require('../../assets/icons/lock.png'),
  mail: require('../../assets/icons/mail.png'),
  mobile: require('../../assets/icons/mobile.png'),
  moon: require('../../assets/icons/moon.png'),
  office: require('../../assets/icons/office.png'),
  offline: require('../../assets/icons/offline.png'),
  party: require('../../assets/icons/party.png'),
  people: require('../../assets/icons/people.png'),
  phone: require('../../assets/icons/phone.png'),
  pin: require('../../assets/icons/pin.png'),
  q_abasare: require('../../assets/icons/q_abasare.png'),
  q_gift: require('../../assets/icons/q_gift.png'),
  q_help: require('../../assets/icons/q_help.png'),
  q_places: require('../../assets/icons/q_places.png'),
  q_ride: require('../../assets/icons/q_ride.png'),
  q_scan: require('../../assets/icons/q_scan.png'),
  q_schedule: require('../../assets/icons/q_schedule.png'),
  q_search: require('../../assets/icons/q_search.png'),
  q_stats: require('../../assets/icons/q_stats.png'),
  qr: require('../../assets/icons/qr.png'),
  question: require('../../assets/icons/question.png'),
  receipt: require('../../assets/icons/receipt.png'),
  recurring: require('../../assets/icons/recurring.png'),
  ride: require('../../assets/icons/ride.png'),
  road: require('../../assets/icons/road.png'),
  school: require('../../assets/icons/school.png'),
  search: require('../../assets/icons/search.png'),
  seat: require('../../assets/icons/seat.png'),
  settings: require('../../assets/icons/settings.png'),
  share: require('../../assets/icons/share.png'),
  shield: require('../../assets/icons/shield.png'),
  silver: require('../../assets/icons/silver.png'),
  siren: require('../../assets/icons/siren.png'),
  sms: require('../../assets/icons/sms.png'),
  star: require('../../assets/icons/star.png'),
  sun: require('../../assets/icons/sun.png'),
  tab_account: require('../../assets/icons/tab_account.png'),
  tab_book: require('../../assets/icons/tab_book.png'),
  tab_car: require('../../assets/icons/tab_car.png'),
  tab_earn: require('../../assets/icons/tab_earn.png'),
  tab_home: require('../../assets/icons/tab_home.png'),
  tab_jobs: require('../../assets/icons/tab_jobs.png'),
  tab_profile: require('../../assets/icons/tab_profile.png'),
  tab_trips: require('../../assets/icons/tab_trips.png'),
  tab_wallet: require('../../assets/icons/tab_wallet.png'),
  tag: require('../../assets/icons/tag.png'),
  tickets: require('../../assets/icons/tickets.png'),
  traffic: require('../../assets/icons/traffic.png'),
  undo: require('../../assets/icons/undo.png'),
  user: require('../../assets/icons/user.png'),
  van: require('../../assets/icons/van.png'),
  wallet: require('../../assets/icons/wallet.png'),
  whatsapp: require('../../assets/icons/whatsapp.png'),
} as const;
export type IconName = keyof typeof ICONS;

export const EMOJI_ICON: Record<string, IconName> = {
  '🚗': 'cars',
  '🆘': 'claims',
  '🧑‍✈️': 'q_abasare',
  '🛵': 'q_ride',
  '🧾': 'tickets',
  '💳': 'credit',
  '📍': 'q_places',
  '⭐': 'star',
  '★': 'star',
  '💰': 'coins',
  '💬': 'q_help',
  '💵': 'cash',
  '🏠': 'tab_home',
  '👤': 'user',
  '🛡️': 'shield',
  '🛡': 'shield',
  '🎁': 'q_gift',
  '🚦': 'traffic',
  '🔒': 'lock',
  '🔐': 'lock',
  '🔓': 'lock',
  '🗺️': 'tab_book',
  '🗺': 'tab_book',
  '🛟': 'claims',
  '🛣️': 'road',
  '🛣': 'road',
  '🎓': 'school',
  '📱': 'mobile',
  '💼': 'briefcase',
  '✅': 'check',
  '🚐': 'van',
  '🚙': 'van',
  '📡': 'offline',
  '📴': 'offline',
  '📊': 'q_stats',
  '▦': 'q_scan',
  '👥': 'people',
  '🤝': 'people',
  '🥇': 'gold',
  '🥈': 'silver',
  '🥉': 'bronze',
  '📨': 'mail',
  '🔎': 'search',
  '🔍': 'q_search',
  '❓': 'question',
  '📁': 'folder',
  '🔁': 'recurring',
  '🪪': 'idcard',
  '🧭': 'compass',
  '🎉': 'party',
  '🎯': 'party',
  '🕐': 'clock',
  '🕘': 'clock',
  '🔢': 'idcard',
  '💺': 'seat',
  '📲': 'mobile',
  '📸': 'camera',
  '📷': 'camera',
  '🏁': 'flag',
  '🌙': 'moon',
  '🚓': 'siren',
  '🚑': 'cross',
  '🔥': 'flame',
  '⏰': 'q_schedule',
  '💡': 'bulb',
  '📅': 'calendar',
  '📏': 'fare',
  '⚙️': 'settings',
  '⚙': 'settings',
  '🧑': 'user',
  '🔗': 'link',
  '🏷': 'tag',
  '🏢': 'office',
  '🖼️': 'camera',
  '🖼': 'camera',
  '📞': 'phone',
  '↩️': 'undo',
  '↩': 'undo',
  '↺': 'undo',
  '🟢': 'check',
};

const EMOJI_RE = /(?:\p{Extended_Pictographic}|\u25A6|\u2605)(?:\uFE0F)?(?:\u200D\p{Extended_Pictographic}\uFE0F?)*/gu;
/** Splits a string such as "🧑‍✈️🚗" into its emoji clusters. */
export const emojiList = (s: string): string[] => s.match(EMOJI_RE) ?? [];
/** `icon:<name>` selects artwork by name; otherwise the emoji is looked up. */
export const iconFor = (g: string | undefined | null): ImageSourcePropType | null => {
  if (g && g.startsWith('icon:')) { const k = g.slice(5) as IconName; return ICONS[k] ?? null; }
  const n = g ? EMOJI_ICON[g] ?? EMOJI_ICON[g.replace(/\uFE0F/g, '')] : undefined; return n ? ICONS[n] : null; };
export const iconByName = (n: IconName): ImageSourcePropType => ICONS[n];
